version: '3.9'

networks:
  default:
    name: 'hdm'

volumes:
  hdm-pg:
  hdm-logs:

services:
  postgres:
    container_name: 'hdm-pg'
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 1777897vova
    ports:
      - "5432:5432"
    volumes:
    - hdm-pg:/var/lib/postgresql/data