version: '3.4'

networks:
 hdm-network:
  driver: bridge

volumes:
  hdm-pg:
  keycloak-pg:

services:

  hdm-api:
   container_name: 'hdm-api'
   image: ${DOCKER_REGISTRY-}hdm-api
   build:
    context: .
    dockerfile: HelpDeskMaster.WebApi/Dockerfile
   profiles: [web]
   ports:
    - "57397:8081"
    - "57398:8080"
   depends_on:
     hdm-postgres:
      condition: service_healthy
   environment:
    ConnectionStrings__HdmDbConnection: 'Host=hdm-postgres;Port=5432;Database=hdm-pg;User ID=postgres;Password=postgres1234;Pooling=true;MinPoolSize=1;MaxPoolSize=20;ConnectionLifeTime=15;Timeout=60;CommandTimeout=8;Trust Server Certificate=True'
    Keycloak__realm: 'hdm-realm'
    Keycloak__auth-server-url: 'http://keycloak:8088/'
    Keycloak__ssl-required: 'none'
    Keycloak__resource: 'hdm-client'
    Keycloak__verify-token-audience: 'False'
    Keycloak__verify-token-issuer: 'False'
    Keycloak__credentials__secret: 'WNMzQVpMkjskGVTZCJB4T5SQ6xPQjJzg'
    Keycloak__confidential-port: '0'
    # EmailSender__Server: ''
    # EmailSender__Port: '0'
    # EmailSender__SenderName: ''
    # EmailSender__SenderEmail: ''
    # EmailSender__UserName: ''
    # EmailSender__Password: ''
    BackgroundJobs__Outbox__Schedule: '0/15 * * * * *'
    BackgroundJobs__Outbox__BatchSize: "15"
    StartOptions__GenerateTestData: 'True'
   networks:
    - hdm-network

  hdm-postgres:
    container_name: 'hdm-pg'
    image: 'postgres:16.2'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: postgres1234
    healthcheck:
     test: "exit 0"
    ports:
      - "5432:5432"
    volumes:
    - hdm-pg:/var/lib/postgresql/data
    networks:
     - hdm-network

  keycloak:
    container_name: 'keycloak'
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloakdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: public
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8088
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      [
        'start-dev',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/opt/keycloak/tmp/import',
        '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING'
      ]
    volumes:
     - ./HelpDeskMaster.WebApi/Authentication/Keycloak/Import:/opt/keycloak/tmp/import
    ports:
        - 8090:8088
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    networks:
     - hdm-network

  keycloak-postgres:
    container_name: 'keycloak-pg'
    image: postgres:16.2
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: admin
    healthcheck:
     test: "exit 0"
    ports:
     - "5433:5432"
    volumes:
     - keycloak-pg:/var/lib/postgresql/data
    networks:
     - hdm-network
